ENTITY("Person"):
    NODE("Person") person:
        + ID = Person.ID # This is a primary attribute, meaning that all Person nodes with the same ID are merged
                         # Only one primary key is possible per node. If no primary keys are specified a new node is created everytime.
        - FirstName = Person.FirstName
        - LastName = append(Person.LastName, " I appended something")
        - Astaticattr = "HelloWorld!"
    CONDITION(NODE("Language"), "resource['FirstName'] == 'Matthias'") language:
        - ShortName = ASSERT_EQ(Person.NativeLanguage, "D")
    RELATION(person, "speaks", language):
        - Since = Person.DateOfBirth