ENTITY("Flower"):
    NODE("Flower") flower:
        - sepal_length = FLOAT(Flower.sepal_length)
        - petal_length = FLOAT(Flower.petal_width)
        - sepal_width = FLOAT(Flower.sepal_width)
        - petal_width = FLOAT(Flower.petal_width)
    NODE("Species", "BioEntity") species:
        + Name = Flower.species
    RELATION(flower, "is", species):
    
ENTITY("Person"):
    NODE("Person") person:
        + ID = INT(Person.ID)
        - FirstName = Person.FirstName
        - LastName = Person.LastName

    RELATION(person, "likes", MATCH("Species", Name=Person.FavoriteFlower)):
        - Since = "4ever"