ENTITY("Flower"):
    NODE("Flower") flower:
        - sepal_length = Flower.sepal_length
        - sepal_width = Flower.sepal_width
        - petal_length = Flower.petal_width
        - petal_width = Flower.petal_width
    UNIQUE(NODE("Species", "BioEntity")) species:
        - Name = Flower.species
    RELATION(flower, "is", species):
    
ENTITY("Person"):
    UNIQUE(NODE("Person")) person:
        - ID = Person.ID
        - FirstName = Person.FirstName
        - LastName = Person.LastName
    RELATION(person, "likes", MATCH("Species", Name=Person.FavoriteFlower)):
        - Since = "4ever"