# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    
  
    services:
          neo4j:
            image: neo4j:latest
            env:
              NEO4J_dbms_security_procedures_unrestricted: apoc.*
              NEO4J_dbms_connector_bolt_enabled: "true"
              NEO4J_apoc_import_file_enabled: "true"
              NEO4J_apoc_export_file_enabled: "true"
              NEO4J_apoc_import_file_use__neo4j__config: "true"
              NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
              NEO4J_dbms_security_auth__enabled: "false"
              NEO4J_dbms_connector_bolt_advertised__address: localhost:7687
              NEO4JLABS_PLUGINS: '["apoc"]'
            options: >-
              --health-cmd "cypher-shell 'match (n) return count(n)'"
              --health-timeout 10s
              --health-retries 20
              --health-interval 10s
              --health-start-period 30s
            ports:
              - 7687:7687
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
